# fly.toml app configuration file generated for flydebug on 2023-09-26T14:04:45-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "flydebug"
primary_region = "sjc"

[build]

[env]
  NODE_ENV = "production"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[checks]
  [checks.status]
    port = 3000
    type = "http"
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/api/inngest"
    protocol = "http"
    tls_skip_verify = false
